name: ForceResourcePack
main: com.milkory.forceresourcepack.ForceResourcePack
version: ${version}
api-version: 1.13

author: Milkory
softdepend: [ Authme, Multiverse-Core ]

commands:
  force-resource-pack:
    aliases: [ frp ]

permissions:
  force-resource-pack.admin:
    children:
      - force-resource-pack.command.reload
      - force-resource-pack.command.push
    default: op

### CUSTOM PLUGIN 2021-08-25 ###